name: CI - Compilation TypeScript
#https://www.yamllint.com : verifier la syntaxe yml
on: 
    push: 
        branches: [main]
    pull_request: 
        branches: [main]

jobs:
    build:
        name: Compiler TypeScript
        runs-on: ubuntu-latest

        steps:
            - name: Checkout du code
              uses: actions/checkout@v4
        
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Installer les dépendances
              run: npm install
        
            - name: Compiler le projet
              run: npm run build
      
            - name: Lister les fichiers compilés
              run: ls -la dist/